package com.qts.biz.risk.grpc;

// Generated by proto-to-java conversion for RiskCheckClient implementation
// This class represents the protobuf message RiskCheckRequestProto

/**
 * Risk Check Request Proto
 * gRPC request message for pre-trade risk validation
 */
public final class RiskCheckRequestProto {
    private final String accountId;
    private final String symbol;
    private final String side;
    private final double price;
    private final int quantity;
    private final double orderAmount;
    private final double totalAssetValue;
    private final double dailyBuyAmount;
    private final double dailySellAmount;
    private final double dailyProfitLoss;

    private RiskCheckRequestProto(Builder builder) {
        this.accountId = builder.accountId;
        this.symbol = builder.symbol;
        this.side = builder.side;
        this.price = builder.price;
        this.quantity = builder.quantity;
        this.orderAmount = builder.orderAmount;
        this.totalAssetValue = builder.totalAssetValue;
        this.dailyBuyAmount = builder.dailyBuyAmount;
        this.dailySellAmount = builder.dailySellAmount;
        this.dailyProfitLoss = builder.dailyProfitLoss;
    }

    public String getAccountId() {
        return accountId;
    }

    public String getSymbol() {
        return symbol;
    }

    public String getSide() {
        return side;
    }

    public double getPrice() {
        return price;
    }

    public int getQuantity() {
        return quantity;
    }

    public double getOrderAmount() {
        return orderAmount;
    }

    public double getTotalAssetValue() {
        return totalAssetValue;
    }

    public double getDailyBuyAmount() {
        return dailyBuyAmount;
    }

    public double getDailySellAmount() {
        return dailySellAmount;
    }

    public double getDailyProfitLoss() {
        return dailyProfitLoss;
    }

    public Builder toBuilder() {
        return new Builder()
                .setAccountId(accountId)
                .setSymbol(symbol)
                .setSide(side)
                .setPrice(price)
                .setQuantity(quantity)
                .setOrderAmount(orderAmount)
                .setTotalAssetValue(totalAssetValue)
                .setDailyBuyAmount(dailyBuyAmount)
                .setDailySellAmount(dailySellAmount)
                .setDailyProfitLoss(dailyProfitLoss);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static final class Builder {
        private String accountId = "";
        private String symbol = "";
        private String side = "";
        private double price = 0.0;
        private int quantity = 0;
        private double orderAmount = 0.0;
        private double totalAssetValue = 0.0;
        private double dailyBuyAmount = 0.0;
        private double dailySellAmount = 0.0;
        private double dailyProfitLoss = 0.0;

        public Builder setAccountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        public Builder setSymbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        public Builder setSide(String side) {
            this.side = side;
            return this;
        }

        public Builder setPrice(double price) {
            this.price = price;
            return this;
        }

        public Builder setQuantity(int quantity) {
            this.quantity = quantity;
            return this;
        }

        public Builder setOrderAmount(double orderAmount) {
            this.orderAmount = orderAmount;
            return this;
        }

        public Builder setTotalAssetValue(double totalAssetValue) {
            this.totalAssetValue = totalAssetValue;
            return this;
        }

        public Builder setDailyBuyAmount(double dailyBuyAmount) {
            this.dailyBuyAmount = dailyBuyAmount;
            return this;
        }

        public Builder setDailySellAmount(double dailySellAmount) {
            this.dailySellAmount = dailySellAmount;
            return this;
        }

        public Builder setDailyProfitLoss(double dailyProfitLoss) {
            this.dailyProfitLoss = dailyProfitLoss;
            return this;
        }

        public RiskCheckRequestProto build() {
            return new RiskCheckRequestProto(this);
        }
    }
}